//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenHack.University.Services.Student
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OpenHack.University.Services.Student.IStudent")]
    public interface IStudent
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/Search", ReplyAction="http://tempuri.org/IStudent/SearchResponse")]
        System.Collections.Generic.List<OpenHack.University.Services.Contract.Student> Search();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/Search", ReplyAction="http://tempuri.org/IStudent/SearchResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<OpenHack.University.Services.Contract.Student>> SearchAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/GetById", ReplyAction="http://tempuri.org/IStudent/GetByIdResponse")]
        OpenHack.University.Services.Contract.Student GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/GetById", ReplyAction="http://tempuri.org/IStudent/GetByIdResponse")]
        System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Student> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/Create", ReplyAction="http://tempuri.org/IStudent/CreateResponse")]
        OpenHack.University.Services.Contract.Student Create(OpenHack.University.Services.Contract.Student studentToCreate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/Create", ReplyAction="http://tempuri.org/IStudent/CreateResponse")]
        System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Student> CreateAsync(OpenHack.University.Services.Contract.Student studentToCreate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/Modify", ReplyAction="http://tempuri.org/IStudent/ModifyResponse")]
        OpenHack.University.Services.Contract.Student Modify(OpenHack.University.Services.Contract.Student studentToModify);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/Modify", ReplyAction="http://tempuri.org/IStudent/ModifyResponse")]
        System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Student> ModifyAsync(OpenHack.University.Services.Contract.Student studentToModify);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/Delete", ReplyAction="http://tempuri.org/IStudent/DeleteResponse")]
        OpenHack.University.Services.Contract.Student Delete(int studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/Delete", ReplyAction="http://tempuri.org/IStudent/DeleteResponse")]
        System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Student> DeleteAsync(int studentId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IStudentChannel : OpenHack.University.Services.Student.IStudent, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class StudentClient : System.ServiceModel.ClientBase<OpenHack.University.Services.Student.IStudent>, OpenHack.University.Services.Student.IStudent
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public StudentClient() : 
                base(StudentClient.GetDefaultBinding(), StudentClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IStudent.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StudentClient(EndpointConfiguration endpointConfiguration) : 
                base(StudentClient.GetBindingForEndpoint(endpointConfiguration), StudentClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StudentClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(StudentClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StudentClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(StudentClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StudentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<OpenHack.University.Services.Contract.Student> Search()
        {
            return base.Channel.Search();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<OpenHack.University.Services.Contract.Student>> SearchAsync()
        {
            return base.Channel.SearchAsync();
        }
        
        public OpenHack.University.Services.Contract.Student GetById(int id)
        {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Student> GetByIdAsync(int id)
        {
            return base.Channel.GetByIdAsync(id);
        }
        
        public OpenHack.University.Services.Contract.Student Create(OpenHack.University.Services.Contract.Student studentToCreate)
        {
            return base.Channel.Create(studentToCreate);
        }
        
        public System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Student> CreateAsync(OpenHack.University.Services.Contract.Student studentToCreate)
        {
            return base.Channel.CreateAsync(studentToCreate);
        }
        
        public OpenHack.University.Services.Contract.Student Modify(OpenHack.University.Services.Contract.Student studentToModify)
        {
            return base.Channel.Modify(studentToModify);
        }
        
        public System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Student> ModifyAsync(OpenHack.University.Services.Contract.Student studentToModify)
        {
            return base.Channel.ModifyAsync(studentToModify);
        }
        
        public OpenHack.University.Services.Contract.Student Delete(int studentId)
        {
            return base.Channel.Delete(studentId);
        }
        
        public System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Student> DeleteAsync(int studentId)
        {
            return base.Channel.DeleteAsync(studentId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IStudent))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IStudent))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:1096/Student.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return StudentClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IStudent);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return StudentClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IStudent);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IStudent,
        }
    }
}
