//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenHack.University.Services.Instructor
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OpenHack.University.Services.Instructor.IInstructor")]
    public interface IInstructor
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstructor/Search", ReplyAction="http://tempuri.org/IInstructor/SearchResponse")]
        System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Instructor[]> SearchAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstructor/GetById", ReplyAction="http://tempuri.org/IInstructor/GetByIdResponse")]
        System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Instructor> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstructor/Create", ReplyAction="http://tempuri.org/IInstructor/CreateResponse")]
        System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Instructor> CreateAsync(OpenHack.University.Services.Contract.Instructor instructorToCreate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstructor/Modify", ReplyAction="http://tempuri.org/IInstructor/ModifyResponse")]
        System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Instructor> ModifyAsync(OpenHack.University.Services.Contract.Instructor instructorToModify);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInstructor/Delete", ReplyAction="http://tempuri.org/IInstructor/DeleteResponse")]
        System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Instructor> DeleteAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IInstructorChannel : OpenHack.University.Services.Instructor.IInstructor, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class InstructorClient : System.ServiceModel.ClientBase<OpenHack.University.Services.Instructor.IInstructor>, OpenHack.University.Services.Instructor.IInstructor
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public InstructorClient() : 
                base(InstructorClient.GetDefaultBinding(), InstructorClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IInstructor.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InstructorClient(EndpointConfiguration endpointConfiguration) : 
                base(InstructorClient.GetBindingForEndpoint(endpointConfiguration), InstructorClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InstructorClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(InstructorClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InstructorClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(InstructorClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InstructorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Instructor[]> SearchAsync()
        {
            return base.Channel.SearchAsync();
        }
        
        public System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Instructor> GetByIdAsync(int id)
        {
            return base.Channel.GetByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Instructor> CreateAsync(OpenHack.University.Services.Contract.Instructor instructorToCreate)
        {
            return base.Channel.CreateAsync(instructorToCreate);
        }
        
        public System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Instructor> ModifyAsync(OpenHack.University.Services.Contract.Instructor instructorToModify)
        {
            return base.Channel.ModifyAsync(instructorToModify);
        }
        
        public System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Instructor> DeleteAsync(int id)
        {
            return base.Channel.DeleteAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IInstructor))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IInstructor))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:1096/Instructor.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return InstructorClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IInstructor);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return InstructorClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IInstructor);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IInstructor,
        }
    }
}
