//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenHack.University.Services.Department
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OpenHack.University.Services.Department.IDepartment")]
    public interface IDepartment
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartment/Search", ReplyAction="http://tempuri.org/IDepartment/SearchResponse")]
        System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Department[]> SearchAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartment/GetById", ReplyAction="http://tempuri.org/IDepartment/GetByIdResponse")]
        System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Department> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartment/Create", ReplyAction="http://tempuri.org/IDepartment/CreateResponse")]
        System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Department> CreateAsync(OpenHack.University.Services.Contract.Department departmentToCreate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartment/Modify", ReplyAction="http://tempuri.org/IDepartment/ModifyResponse")]
        System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Department> ModifyAsync(OpenHack.University.Services.Contract.Department departmentToModify);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartment/Delete", ReplyAction="http://tempuri.org/IDepartment/DeleteResponse")]
        System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Department> DeleteAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IDepartmentChannel : OpenHack.University.Services.Department.IDepartment, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class DepartmentClient : System.ServiceModel.ClientBase<OpenHack.University.Services.Department.IDepartment>, OpenHack.University.Services.Department.IDepartment
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DepartmentClient() : 
                base(DepartmentClient.GetDefaultBinding(), DepartmentClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IDepartment.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DepartmentClient(EndpointConfiguration endpointConfiguration) : 
                base(DepartmentClient.GetBindingForEndpoint(endpointConfiguration), DepartmentClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DepartmentClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DepartmentClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DepartmentClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DepartmentClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DepartmentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Department[]> SearchAsync()
        {
            return base.Channel.SearchAsync();
        }
        
        public System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Department> GetByIdAsync(int id)
        {
            return base.Channel.GetByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Department> CreateAsync(OpenHack.University.Services.Contract.Department departmentToCreate)
        {
            return base.Channel.CreateAsync(departmentToCreate);
        }
        
        public System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Department> ModifyAsync(OpenHack.University.Services.Contract.Department departmentToModify)
        {
            return base.Channel.ModifyAsync(departmentToModify);
        }
        
        public System.Threading.Tasks.Task<OpenHack.University.Services.Contract.Department> DeleteAsync(int id)
        {
            return base.Channel.DeleteAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IDepartment))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IDepartment))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:1096/Department.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DepartmentClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IDepartment);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DepartmentClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IDepartment);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IDepartment,
        }
    }
}
